var searchData=
[
  ['b_0',['b',['../structhueplusplus_1_1_r_g_b.html#a7f0452178ad85616ff065cf56915b6f4',1,'hueplusplus::RGB']]],
  ['baseclip_1',['baseclip',['../classhueplusplus_1_1sensors_1_1_base_c_l_i_p.html',1,'hueplusplus::sensors::BaseCLIP'],['../classhueplusplus_1_1sensors_1_1_base_c_l_i_p.html#a3c40f4b4e9c742f876e51968651eb810',1,'hueplusplus::sensors::BaseCLIP::BaseCLIP()']]],
  ['basedevice_2',['basedevice',['../classhueplusplus_1_1_base_device.html',1,'hueplusplus::BaseDevice'],['../classhueplusplus_1_1_base_device.html#aaa90386c0cea99464dee6bedb2c68254',1,'hueplusplus::BaseDevice::BaseDevice(int id, const HueCommandAPI &amp;commands, const std::string &amp;path, std::chrono::steady_clock::duration refreshDuration, const nlohmann::json &amp;currentState)'],['../classhueplusplus_1_1_base_device.html#a48bf88e758fd7191c599a46751755c97',1,'hueplusplus::BaseDevice::BaseDevice(int id, const std::shared_ptr&lt; APICache &gt; &amp;baseCache)']]],
  ['basedevice_2ecpp_3',['BaseDevice.cpp',['../_base_device_8cpp.html',1,'']]],
  ['basedevice_2eh_4',['BaseDevice.h',['../_base_device_8h.html',1,'']]],
  ['basehttphandler_5',['BaseHttpHandler',['../classhueplusplus_1_1_base_http_handler.html',1,'hueplusplus']]],
  ['basehttphandler_2ecpp_6',['BaseHttpHandler.cpp',['../_base_http_handler_8cpp.html',1,'']]],
  ['basehttphandler_2eh_7',['BaseHttpHandler.h',['../_base_http_handler_8h.html',1,'']]],
  ['basic_20installation_8',['basic installation',['../index.html#autotoc_md14',1,'Basic installation'],['../build.html#basic-install',1,'Basic installation']]],
  ['bluecorner_9',['blueCorner',['../structhueplusplus_1_1_color_gamut.html#a9300f0d4b86be5dfae499f4e4d61c9a8',1,'hueplusplus::ColorGamut']]],
  ['bridge_10',['bridge',['../classhueplusplus_1_1_bridge.html#a5fa0378ab3552a82d611fba6701bcad6',1,'hueplusplus::Bridge::Bridge()'],['../classhueplusplus_1_1_entertainment_mode.html#a3be4ee9ee045fc791e2606c78fbfd3e6',1,'hueplusplus::EntertainmentMode::bridge'],['../classhueplusplus_1_1_bridge.html',1,'hueplusplus::Bridge'],['../getting-started.html#autotoc_md1',1,'Creating the Hue bridge']]],
  ['bridge_2ecpp_11',['Bridge.cpp',['../_bridge_8cpp.html',1,'']]],
  ['bridge_2eh_12',['Bridge.h',['../_bridge_8h.html',1,'']]],
  ['bridgeconfig_13',['bridgeconfig',['../classhueplusplus_1_1_bridge_config.html',1,'hueplusplus::BridgeConfig'],['../classhueplusplus_1_1_bridge_config.html#a9ea231a17f231f44230f1d99a91be9cd',1,'hueplusplus::BridgeConfig::BridgeConfig(std::shared_ptr&lt; APICache &gt; baseCache, std::chrono::steady_clock::duration refreshDuration)'],['../classhueplusplus_1_1_bridge_config.html#aba7cc6034b4c95f8e2df4e19c53a8dac',1,'hueplusplus::BridgeConfig::BridgeConfig(const BridgeConfig &amp;)=default'],['../classhueplusplus_1_1_bridge_config.html#a0ef3ef7f8f2c0bbd53e713c005466b21',1,'hueplusplus::BridgeConfig::BridgeConfig(BridgeConfig &amp;&amp;)=default']]],
  ['bridgeconfig_2ecpp_14',['BridgeConfig.cpp',['../_bridge_config_8cpp.html',1,'']]],
  ['bridgeconfig_2eh_15',['BridgeConfig.h',['../_bridge_config_8h.html',1,'']]],
  ['bridgefinder_16',['bridgefinder',['../classhueplusplus_1_1_bridge_finder.html',1,'hueplusplus::BridgeFinder'],['../classhueplusplus_1_1_bridge.html#a1ffb423a79da8deb2ef13bb2c89b6d78',1,'hueplusplus::Bridge::BridgeFinder'],['../classhueplusplus_1_1_bridge_finder.html#a84d4cd53894f7a1e9bde97998e59f274',1,'hueplusplus::BridgeFinder::BridgeFinder(std::shared_ptr&lt; const IHttpHandler &gt; handler)']]],
  ['bridgeidentification_17',['BridgeIdentification',['../structhueplusplus_1_1_bridge_finder_1_1_bridge_identification.html',1,'hueplusplus::BridgeFinder']]],
  ['bridgerequestdelay_18',['bridgeRequestDelay',['../classhueplusplus_1_1_config.html#a736688630986956a1e97e62218403ab3',1,'hueplusplus::Config']]],
  ['bridges_19',['bridges',['../getting-started.html#autotoc_md2',1,'Authenticate Bridges'],['../index.html#autotoc_md11',1,'Authenticate Bridges'],['../index.html#autotoc_md10',1,'Searching for Bridges']]],
  ['bridgesetup_2ecpp_20',['BridgeSetup.cpp',['../_bridge_setup_8cpp.html',1,'']]],
  ['brightness_21',['brightness',['../structhueplusplus_1_1_x_y_brightness.html#a028af75d7418fdccd22d0027f83298cf',1,'hueplusplus::XYBrightness']]],
  ['brightnessstrategy_22',['brightnessstrategy',['../classhueplusplus_1_1_light.html#af9948baaf52a9ce2ed0f145368492873',1,'hueplusplus::Light::brightnessStrategy'],['../classhueplusplus_1_1_brightness_strategy.html',1,'hueplusplus::BrightnessStrategy']]],
  ['brightnessstrategy_2eh_23',['BrightnessStrategy.h',['../_brightness_strategy_8h.html',1,'']]],
  ['build_20and_20install_24',['build and install',['../build.html',1,'Build and install'],['../index.html#autotoc_md13',1,'Build and install']]],
  ['build_20with_20cmake_25',['Build with CMake',['../build.html#build-cmake',1,'']]],
  ['build_2emd_26',['Build.md',['../_build_8md.html',1,'']]],
  ['building_20examples_27',['Building examples',['../build.html#build-examples',1,'']]],
  ['building_20tests_28',['Building tests',['../build.html#build-tests',1,'']]]
];
